### PR TITLE
Merging in updates from main repo

### PR DESCRIPTION
**Pull request by rpate027**

### CODE REVIEW

**Comment by rpate027** [comment]
Updated main repo.

**Review by rpate027 — COMMENTED** [review]
Done reviewing.

**Review by weiglemc — CHANGES_REQUESTED** [review]
@rpate027 Since this isn't an ODU dissertation, please add the university and also the link to the document in the university's repository (https://scholarworks.wm.edu/etd/1550153840/).

**Comment by rpate027** [comment]
@weiglemc added the university and the link to the university's repository.

**Comment by rpate027** [comment]
@weiglemc pull request is open now.

**Pull request merged**
